# Generated by Django 5.2.9 on 2025-12-08 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hamburguesa',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='hamburguesas/'),
        ),
    ]
