# Generated by Django 5.2.9 on 2025-12-09 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_hamburguesa_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformacionNegocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('horario_atencion', models.TextField(help_text='Ej: Lun-Vie 18hs a 23 hs')),
            ],
        ),
    ]
