# Generated by Django 5.2.9 on 2025-12-14 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_categoria_hamburguesa_es_oferta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpcionesExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(help_text='Clasificación de la opción (ej: Aderezo, Extra, Pan)', max_length=50)),
                ('precio_adicional', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
    ]
