# Generated by Django 5.2.9 on 2025-12-20 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_opcionesextra'),
    ]

    operations = [
        migrations.AddField(
            model_name='hamburguesa',
            name='ingredientes_default',
            field=models.CharField(default='Tomate, Lechuga', help_text='Separados por coma', max_length=255),
        ),
        migrations.AddField(
            model_name='hamburguesa',
            name='permite_doble',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hamburguesa',
            name='permite_simple',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hamburguesa',
            name='permite_triple',
            field=models.BooleanField(default=True),
        ),
    ]
