# Generated by Django 5.2.9 on 2025-12-27 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_hamburguesa_ingredientes_default_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informacionnegocio',
            name='email',
        ),
        migrations.AddField(
            model_name='informacionnegocio',
            name='instagram',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
