# Generated by Django 5.2.9 on 2025-12-27 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_informacionnegocio_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informacionnegocio',
            name='direccion',
        ),
        migrations.AddField(
            model_name='informacionnegocio',
            name='zona_atencion',
            field=models.CharField(default='La Plata', max_length=200),
        ),
    ]
