# Generated by Django 5.2.9 on 2025-12-31 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_informacionnegocio_direccion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hamburguesa',
            name='precio',
        ),
        migrations.AddField(
            model_name='hamburguesa',
            name='precio_doble',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='hamburguesa',
            name='precio_simple',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='hamburguesa',
            name='precio_triple',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
