# Generated by Django 5.2.9 on 2025-12-31 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_extra_hamburguesa_papas_sason'),
    ]

    operations = [
        migrations.AddField(
            model_name='extra',
            name='cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.categoria'),
        ),
        migrations.AlterField(
            model_name='extra',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Solo ingresar si tiene valor adicional', max_digits=10),
        ),
    ]
