# Generated by Django 5.2.9 on 2026-01-04 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_cat_remove_extra_cat_extra_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extra',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='core.cat'),
        ),
    ]
