# Generated by Django 5.2.9 on 2026-01-06 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_bebidas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bebidas',
            new_name='bebida',
        ),
    ]
